sudo: false
language: node_js
cache: yarn
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
script:
  - yarn lint
  - yarn test
after_success:
  - yarn semantic-release
